# Generated by Django 4.2.18 on 2025-02-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PeriodoInforme', models.DateField()),
                ('RUT', models.CharField(max_length=20, unique=True)),
                ('RazonSocial', models.CharField(max_length=255)),
                ('Planta', models.CharField(max_length=255)),
                ('PuntoDeDescarga', models.CharField(max_length=255)),
                ('CuerpoReceptor', models.CharField(max_length=255)),
                ('Norma', models.CharField(max_length=50)),
                ('Muestra', models.PositiveIntegerField()),
                ('Parametro', models.CharField(max_length=255)),
                ('Unidad', models.CharField(max_length=50)),
                ('ValorReportado', models.FloatField()),
                ('TipoDeControl', models.CharField(max_length=100)),
                ('Laboratorio', models.CharField(max_length=255)),
                ('UnidadFiscalizable', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ComunaId', models.PositiveIntegerField()),
                ('comuna', models.CharField(max_length=255)),
                ('NombreCategoria', models.CharField(max_length=255)),
                ('NombreSubCategoria', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('NumeroRCA', models.PositiveIntegerField()),
                ('FechaRCA', models.DateField()),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'formulario_reporte',
            },
        ),
    ]
