# Generated by Django 5.1.6 on 2025-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={},
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ComunaId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Muestra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='NumeroRCA',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='RUT',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reporte',
        ),
    ]
