# Generated by Django 5.1.6 on 2025-02-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_reporte_options_alter_reporte_comunaid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reporte',
            table='formulario_reporte',
        ),
    ]
